#+STARTUP: overview
#+TITLE: emacs config
#+CREATOR: dovydas@slaptavieta.lt
#+LANGUAGE: en
#+OPTIONS: num:nil
#+ATTR_HTML: :style margin-left: auto; margin-right: auto;

* Look & feel
** General
*** Enable GC
#+BEGIN_SRC emacs-lisp
(add-hook 'focus-out-hook #'garbage-collect)
#+END_SRC
*** Async
Use asynchronous processes wherever possible
#+BEGIN_SRC emacs-lisp
  (use-package async
    :ensure t
    :init (dired-async-mode 1)
(async-bytecomp-package-mode 1))
#+END_SRC
*** OS X PATH for Emacs
Initializes PATH for Emacs when running inside OS X
#+BEGIN_SRC emacs-lisp
  (when (memq window-system '(mac ns x))
    (use-package exec-path-from-shell
      :ensure t
      :config
      (exec-path-from-shell-initialize)))
#+END_SRC
** Visual
#+BEGIN_SRC emacs-lisp
  (use-package zerodark-theme
    :ensure t
    :init
      (load-theme 'zerodark t))
#+END_SRC
** Modeline
Use spacemacs modeline with theme
#+BEGIN_SRC emacs-lisp
  (use-package spaceline
    :ensure t
    :config
    (require 'spaceline-config)
      (setq powerline-default-separator (quote arrow))
      (spaceline-spacemacs-theme))
#+END_SRC
** Editor behaviour
*** Paren mode
#+BEGIN_SRC emacs-lisp
  (show-paren-mode 1)
  (setq show-paren-style 'expression)
#+END_SRC
*** Use spaces for tabs
For consistency
#+BEGIN_SRC emacs-lisp
  (setq-default indent-tabs-mode nil)
#+END_SRC
*** Electric
Matching characters
#+BEGIN_SRC emacs-lisp
  (setq electric-pair-pairs '(
                               (?\{ . ?\})
                               (?\( . ?\))
                               (?\[ . ?\])
                               (?\" . ?\")
                               (?\' . ?\')
                             ))
  (electric-pair-mode t)
#+END_SRC
*** Expand region
Expand selection region C-q
#+BEGIN_SRC emacs-lisp
  (use-package expand-region
    :ensure t
    :bind ("C-q" . er/expand-region))
#+END_SRC
*** Hungry deletion
Delete extra whitespace
#+BEGIN_SRC emacs-lisp
  (use-package hungry-delete
    :ensure t
    :config
      (global-hungry-delete-mode))
#+END_SRC
*** Zapping to char
A nifty little package that kills all text between your cursor and a selected character.
A lot more useful than you might think. If you wish to include the selected character in the killed region,
change =zzz-up-to-char= into =zzz-to-char=.
#+BEGIN_SRC emacs-lisp
  (use-package zzz-to-char
    :ensure t
    :bind ("M-z" . zzz-up-to-char))
#+END_SRC
*** Rainbow delimiters
Show matching parenthesis by colour
#+BEGIN_SRC emacs-lisp
  (use-package rainbow-delimiters
    :ensure t
    :config
    (add-hook 'prog-mode-hook #'rainbow-delimiters-mode))
#+END_SRC
*** Jump tot character
M-s to jump to character
#+BEGIN_SRC emacs-lisp
  (use-package avy
    :ensure t
    :bind
      ("M-s" . avy-goto-char))
#+END_SRC
*** Following window splits
After you split a window, your focus remains in the previous one.
#+BEGIN_SRC emacs-lisp
  (defun split-and-follow-horizontally ()
    (interactive)
    (split-window-below)
    (balance-windows)
    (other-window 1))
  (global-set-key (kbd "C-x 2") 'split-and-follow-horizontally)
  (defun split-and-follow-vertically ()
    (interactive)
    (split-window-right)
    (balance-windows)
    (other-window 1))
  (global-set-key (kbd "C-x 3") 'split-and-follow-vertically)
#+END_SRC
** Misc
*** Disable menus and scrollbars
#+BEGIN_SRC emacs-lisp
  (tool-bar-mode -1)
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
#+END_SRC
*** Show 80 column marker
#+BEGIN_SRC emacs-lisp
  (defun prog-mode-header-line ()
    "Setup the `header-line-format' on for buffers."
    (setq header-line-format
          (list " " (make-string 79 ?-) "|")))
  (add-hook 'prog-mode-hook #'prog-mode-header-line)
#+END_SRC
*** yes-or-no to y-or-n questions
#+BEGIN_SRC emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC
*** Disable bell
#+BEGIN_SRC emacs-lisp
  (setq ring-bell-function 'ignore)
#+END_SRC
*** Beacon
Show cursor position when switching windows
#+BEGIN_SRC emacs-lisp
  (use-package beacon
    :ensure t
    :config
      (beacon-mode 1))
#+END_SRC
*** Highlight current line
#+BEGIN_SRC emacs-lisp
  (when window-system (add-hook 'prog-mode-hook 'hl-line-mode))
#+END_SRC

*** which-key
#+BEGIN_SRC emacs-lisp
  (use-package which-key
    :ensure t
    :config
      (which-key-mode))
#+END_SRC
** Configuration management
*** Visiting the configuration
Quickly edit =~/config.org= C-c e
#+BEGIN_SRC emacs-lisp
  (defun config-visit ()
    (interactive)
    (find-file "~/.emacs.d/config.org"))
  (global-set-key (kbd "C-c e") 'config-visit)
#+END_SRC
*** Reloading the configuration
Reload configration with C-x r
#+BEGIN_SRC emacs-lisp
  (defun config-reload ()
    "Reloads ~/.emacs.d/config.org at runtime"
    (interactive)
    (org-babel-load-file (expand-file-name "~/.emacs.d/config.org")))
  (global-set-key (kbd "C-x r") 'config-reload)
#+END_SRC

* Dashboard
Startup screen
#+BEGIN_SRC emacs-lisp
(use-package dashboard
        :ensure t
        :config
          (dashboard-setup-startup-hook)
          (setq dashboard-items '((recents  . 5)
                                  (projects . 5))))
#+END_SRC
* Navigation
** Ivy
#+BEGIN_SRC emacs-lisp
    (use-package ivy
      :ensure t
    :config
  (ivy-mode 1)
(setq ivy-use-virtual-buffers t)
(setq enable-recursive-minibuffers t)
(global-set-key (kbd "C-c C-r") 'ivy-resume)
(global-set-key (kbd "<f6>") 'ivy-resume))
#+END_SRC
** Improved search
#+BEGIN_SRC emacs-lisp
  (use-package swiper
    :ensure t
    :bind ("C-s" . 'swiper))
#+END_SRC
** Counsel
Autocomplete
#+BEGIN_SRC emacs-lisp
  (use-package counsel
    :ensure t
    :config 
    (counsel-mode 1))
#+END_SRC
** Commands
Options are SMEX, AMX, smex-helm
#+BEGIN_SRC emacs-lisp
  (use-package smex
    :ensure t)
#+END_SRC
** Company mode
Autocomplete
#+BEGIN_SRC emacs-lisp
  (use-package company
                  :ensure t
                  :config
                  (global-company-mode)
                  (setq company-idle-delay 1)
                  (setq company-minimum-prefix-length 2)
                  (add-hook 'after-init-hook 'global-company-mode)
                  (add-hook 'org-mode-hook #'add-pcomplete-to-capf)
                  (setq company-backends '((company-capf company-files company-elisp company-yasnippet) (company-dabbrev company-dabbrev-code)))
                  (bind-key [remap completion-at-point] #'company-complete company-mode-map)
  )
#+END_SRC
* Org mode
** Common settings
#+BEGIN_SRC emacs-lisp
  (setq org-ellipsis " ")
  (setq org-src-fontify-natively t)
  (setq org-src-tab-acts-natively t)
  (setq org-confirm-babel-evaluate nil)
  (setq org-export-with-smart-quotes t)
  (setq org-src-window-setup 'current-window)
  (add-hook 'org-mode-hook 'org-indent-mode)
#+END_SRC
** Line wrapping
#+BEGIN_SRC emacs-lisp
  (add-hook 'org-mode-hook
	    '(lambda ()
	       (visual-line-mode 1)))
#+END_SRC
** Keybindings
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c '") 'org-edit-src-code)
#+END_SRC
** Easy-to-add emacs-lisp template
Hitting tab after an "<el" in an org-mode file will create a template for elisp insertion.
#+BEGIN_SRC emacs-lisp
  (add-to-list 'org-structure-template-alist
	       '("el" "#+BEGIN_SRC emacs-lisp\n?\n#+END_SRC"))
#+END_SRC
* Projects
Projectile is an awesome project manager, mostly because it recognizes directories
with a =.git= directory as projects and helps you manage them accordingly.
C-c p s    Switch to project
C-c p f    List files in a project
C-c p k    Kill all buffers related to current project
** Enable projectile globally
This makes sure that everything can be a project.
#+BEGIN_SRC emacs-lisp
  (use-package projectile
      :ensure t
      :init
        (projectile-mode 1)
  )
#+END_SRC
** Let projectile call make
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "<f5>") 'projectile-compile-project)
#+END_SRC
** NeoTree
Toggle NeoTree with <f8>
Will switch to current projectile project on project switch
#+BEGIN_SRC emacs-lisp
  (use-package neotree
  :ensure t
  :init
  (neotree)
  :config
  (global-set-key [f8] 'neotree-toggle)
  ;; (setq neo-autorefresh nil)
  (setq neo-smart-open t)
  ;; projectile-switch-project (C-c p p)
  ;; move to to file root
  (setq projectile-switch-project-action 'neotree-projectile-action)
    (defun neotree-project-dir ()
      "Open NeoTree using the git root."
      (interactive)
      (let ((project-dir (projectile-project-root))
            (file-name (buffer-file-name)))
        (neotree-toggle)
        (if project-dir
            (if (neo-global--window-exists-p)
                (progn
                  (neotree-dir project-dir)
                  (neotree-find file-name)))
          (message "Could not find git project root."))))
   (global-set-key [f8] 'neotree-project-dir)
  )
#+END_SRC
** Other to try:
- https://github.com/sabof/project-explorer
- http://cedet.sourceforge.net/speedbar.shtml
- https://github.com/jrockway/eproject
* Dev
Minor, non-completion related settings and plugins for writing code.
** yasnippet
#+BEGIN_SRC emacs-lisp
  (use-package yasnippet
    :ensure t
    :config
      (use-package yasnippet-snippets
        :ensure t)
      (yas-global-mode 1)
      (yas-reload-all))
#+END_SRC
** flycheck
#+BEGIN_SRC emacs-lisp
    (use-package flycheck
      :ensure t
      :init (global-flycheck-mode))
#+END_SRC
** Company quickhelp
#+BEGIN_SRC emacs-lisp
(use-package company-quickhelp          ; Documentation popups for Company
  :ensure t
  :defer t
  :init (add-hook 'global-company-mode-hook #'company-quickhelp-mode))
#+END_SRC
** Tools
*** ripgrep
Allows searching text with ripgrep from within Emacs
#+BEGIN_SRC emacs-lisp
  (use-package rg
      :ensure t
      :defer t
      :config
      (rg-enable-default-bindings))
#+END_SRC
** Languages
*** PHP
#+BEGIN_SRC emacs-lisp
(use-package php-mode ; 
    :ensure t
    :defer t)
#+END_SRC
*** YAML
#+BEGIN_SRC emacs-lisp
(use-package yaml-mode
  :ensure t
  :delight yaml-mode "YAML"
  :mode "\\.yml\\'")
#+END_SRC
*** Rust
Enable rust-mode
#+BEGIN_SRC emacs-lisp
  (use-package rust-mode
    :ensure t
    :config
    (setq rust-rustfmt-bin "~/.cargo/bin/rustfmt")
    (setq rust-format-on-save t))
#+END_SRC
Enable racer completition with company
#+BEGIN_SRC emacs-lisp
  (use-package racer
    :ensure t
    :config
    (add-hook 'rust-mode-hook #'racer-mode)
    (add-hook 'racer-mode-hook #'eldoc-mode)
    (define-key rust-mode-map (kbd "TAB") #'company-indent-or-complete-common)
    (setq company-tooltip-align-annotations t))
#+END_SRC
Cargo mode
#+BEGIN_SRC emacs-lisp
  (use-package cargo
    :ensure t
    :config
    (add-hook 'rust-mode-hook #'cargo-minor-mode))
#+END_SRC
Fly check for rust
#+BEGIN_SRC emacs-lisp
  (use-package flycheck-rust
    :ensure t
    :config
    (add-hook 'flycheck-mode-hook #'flycheck-rust-setup))
#+END_SRC
*** Groovy
#+BEGIN_SRC emacs-lisp
(use-package groovy-mode
:ensure t
:mode "\\.groovy\\'")
#+END_SRC

*** Markdown
#+BEGIN_SRC emacs-lisp
(use-package markdown-mode
:ensure t
;; Default to GitHub-flavored MD
:mode("\\.md$" . gfm-mode))
#+END_SRC
* SCM
** magit
Git management
#+BEGIN_SRC emacs-lisp
  (use-package magit
      :ensure t
      :config
      (setq magit-push-always-verify nil)
      (setq git-commit-summary-max-length 50)
      :bind
      ("M-g" . magit-status))
      (setenv "SSH_ASKPASS" "git-gui--askpass")
#+END_SRC
